# Generated by Django 3.1 on 2020-09-17 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('harga', models.FloatField()),
                ('digital', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_pesanan', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaksi_id', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toko.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Itempesan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumlah', models.IntegerField(blank=True, default=0, null=True)),
                ('waktu_penambah', models.DateTimeField(auto_now_add=True)),
                ('pesan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toko.pesan')),
                ('produk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toko.produk')),
            ],
        ),
        migrations.CreateModel(
            name='IDpesan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idgame', models.CharField(max_length=200, null=True)),
                ('servergame', models.CharField(max_length=200, null=True)),
                ('waktu_penambah', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toko.customer')),
                ('pesan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toko.pesan')),
            ],
        ),
    ]
