# Generated by Django 3.1 on 2020-09-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_auto_20200920_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempesan',
            old_name='Jumlah',
            new_name='jumlah',
        ),
    ]
